# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 704abdedef25f228fd35b9eb5595f4908448699095ea86111c2571ded29c5a5ce25fdcc2ac187344ab2a22e450b7348869f7db86a5153acf302ef14df34e63b3

test:
  secret_key_base: e500f99bff998d58da5e897496b3b6fd26afd5932c1cbe15dd9d8961e309ab08653e6043af4333eb0a267edc9e601e8df8be2ca52dbf2ea4b310b202ce629b84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
